### PR TITLE
✨CSS refactored issue#42 solved✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
i hope the CSS is working properly like before, @andoriyaprashant please review this.
Thank you!

### CODE REVIEW

**Comment by andoriyaprashant** [comment]
Hello @T-Rahul-prabhu-38  , everything else is fine, but this won't run until the home.html file is found. So, you'll need to make this change in the settings: 'DIRS': [os.path.join(BASE_DIR, 'Docs', 'templates', 'html')], and you'll also need to import os.

image

**Comment by T-Rahul-prabhu-38** [comment]
so should i do exactly.

**Comment by andoriyaprashant** [comment]
> so should i do exactly.

Yes

**Comment by T-Rahul-prabhu-38** [comment]
im sorry , i meant to type what should i do.

**Comment by andoriyaprashant** [comment]
> im sorry , i meant to type what should i do.

Just replace "        'DIRS': [
            BASE_DIR / "Docs" / "templates",
        ]," 
to

DIRS': [os.path.join(BASE_DIR, 'Docs', 'templates', 'html')],

In setting.py of DevDocsHub folder 

And also import os in settings.py

**Comment by T-Rahul-prabhu-38** [comment]
ok ill dothat.

**Pull request closed without merging**
