### PR TITLE
added templates , about us and contact us

### PR DESCRIPTION
**Pull request by aditya07389**
---
name: Pull Request Template
description: Template for submitting a pull request
title: "[PR] - About us and Contact us templates"
labels: gssoc extd , hacktoberfest,level 3''
assignees: ''

---

## Description
I have added a about us page and added the content in it which i found relavent , kindly make changes with the text according to your goals, the screenshot :
image

this is the contact us page i added :
image

## Related Issue
fixes issue #102 

Please add the labels gssoc extd,hacktoberfest and level 3
Thankyou , looking forward to contributing more to your project

### CODE REVIEW

**Comment by aditya07389** [comment]
@thestuti can u please merge

**Comment by MastanSayyad** [comment]
@thestuti and @andoriyaprashant Please review this PR and merge if possible, dont let it be open

**Comment by thestuti** [comment]
please resolve the conflicts!

**Comment by aditya07389** [comment]
@thestuti done

**Comment by thestuti** [comment]
i think it's a deployment issue, i'll talk to prashant about it.

**Comment by aditya07389** [comment]
@thestuti cd u pls add the labels/tags

**Comment by thestuti** [comment]
sure

**Comment by aditya07389** [comment]
Thankyou

**Comment by aditya07389** [comment]
If there is anything else you would want me to work on, please tell i would love to !

**Pull request merged**
