### PR TITLE
adding social media username

### PR DESCRIPTION
**Pull request by Aazib-at-hub**
---
name: adding social media usernames
description: #101 
title: "[PR] - social media username"
labels: 'gssocext', 'hacktoberfest'
assignees: 'Aazib-at-hub'

---

## Description
adding social media username so that if a person wants to follow later on he can remember the username.

## Related Issue
#101 

## Type of Change
- [ ] Bug fix
- [x] New feature
- [x] Enhancement
- [ ] Documentation update

## Checklist
- [x] I have read the contributing guidelines.
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have updated the documentation (if applicable).

## Additional Context
Add any other context about the pull request here.

### CODE REVIEW

**Comment by Aazib-at-hub** [comment]
@andoriyaprashant?

**Comment by thestuti** [comment]
thank you!

**Comment by Aazib-at-hub** [comment]
> thank you!

@thestuti please add the labels of gssocextd and hacktoberfest

**Comment by thestuti** [comment]
sorry for the delay, i just came home from school.

**Comment by sanjay-kv** [comment]
@thestuti you missed to add labels

**Comment by thestuti** [comment]
i added

**Comment by sanjay-kv** [comment]
@thestuti you forgot to add labels to it like level1

**Pull request merged**
