### PR TITLE
✨CSS refactored ✨

### PR DESCRIPTION
**Pull request by T-Rahul-prabhu-38**
The inline Css is removed , this will improve the overall performance.
@andoriyaprashant  please have a look at this PR.

### CODE REVIEW

**Comment by T-Rahul-prabhu-38** [comment]
can you please review this 
thank you :)

**Comment by T-Rahul-prabhu-38** [comment]
@andoriyaprashant can you please review this PR.

**Comment by andoriyaprashant** [comment]
Hello @T-Rahul-prabhu-38 

You’ve done the work correctly, but I need the homepage to look like it did before because earlier it looked like

image

And now it looks like this. So, make the necessary changes to the homepage, and then I’ll merge it.

image

**Comment by T-Rahul-prabhu-38** [comment]
SURE ILL , fit it in sometime.

**Pull request closed without merging**
