### PR TITLE
solve BUG: No Link Attach to Languages tab in Navbar #135

### PR DESCRIPTION
**Pull request by Baig-fatema**
---
name: BUG: No Link Attach to Languages tab in Navbar #135
description: Template for submitting a pull request
title: "[PR] -  BUG: No Link Attach to Languages tab in Navbar #135"
labels: gssoc, gssoc-extd, hactoberfesr''
assignees: @andoriyaprashant ''

---

## Description

1.  Added link to languages tab in every page navbar
2. Added url for languages page
3. added view for languages page
Screenshot (111)

## Related Issue #135
If applicable, please reference any related issue (e.g., `#135`).

## Type of Change
- [x] Bug fix
- [ ] New feature
- [ ] Enhancement
- [ ] Documentation update

## Checklist
- [x] I have read the contributing guidelines.
- [x] My code follows the code style of this project.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I have updated the documentation (if applicable).

## Additional Context
Add any other context about the pull request here.

### CODE REVIEW

**Comment by Baig-fatema** [comment]
@andoriyaprashant  please review it.
and add labels please assign this to me.

**Comment by Baig-fatema** [comment]
@andoriyaprashant  Please Review it.

**Comment by Baig-fatema** [comment]
@andoriyaprashant please review it and merge it add my point to leader board.

**Comment by Baig-fatema** [comment]
@andoriyaprashant please review it because i have to made another PR for issue #134  which is assign to me.
until my first PR is not merged  or final i am not able made 2nd PR.
so, please review it and merge it.

**Comment by thestuti** [comment]
please resolve the conflicts!

**Pull request closed without merging**
